version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URI=mongodb+srv://Mokles:123456789Mokles@cluster0.ausxxs0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    container_name: zeradminedash_backend

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: zeradminedash_frontend
